language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajuljulian/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajuljulian/react-test npm test -- --coverage

after_success:
  - docker build -t ajuljulian/multi-client ./client
  - docker build -t ajuljulian/multi-nginx ./nginx
  - docker build -t ajuljulian/multi-server ./server
  - docker build -t ajuljulian/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub.
  - docker push ajuljulian/multi-client
  - docker push ajuljulian/multi-nginx
  - docker push ajuljulian/multi-server
  - docker push ajuljulian/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker-2'
  env: 'Multidocker2-env'
  bucket_name: 'elasticbeanstalk-us-west-2-595374821637'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
